extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/*.bril'
timeout = 15

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.myopt]
pipeline = [
    "bril2json",
    "python bril-jit.py",
    "brili -p {args}",
]